language: node_js
node_js:
  - 6
services:
  - mongodb
before_install:
  - npm install -g npm
  - npm config set spin false
install:
  - npm install
before_script:
  - enb make
  - node common.blocks/app/models/sync.js
script:
- npm test
